/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'tertiary-fixed': '#ebe1d6',
        'on-tertiary': '#353028',
        'on-primary-fixed': '#2c1600',
        'surface-container-highest': '#353535',
        'tertiary-fixed-dim': '#cec5bb',
        'secondary-fixed-dim': '#dec1af',
        'on-tertiary-fixed': '#1f1b14',
        'outline-variant': '#50453b',
        'on-surface': '#e5e2e1',
        error: '#ffb4ab',
        'on-error-container': '#ffdad6',
        'inverse-primary': '#7d562d',
        'tertiary-container': '#b4aba1',
        secondary: '#dec1af',
        tertiary: '#cfc6bc',
        'secondary-container': '#574335',
        'primary-fixed-dim': '#f0bd8b',
        'on-primary-fixed-variant': '#623f18',
        'surface-container-low': '#1c1b1b',
        'on-secondary-fixed-variant': '#574335',
        'inverse-on-surface': '#313030',
        'on-secondary-fixed': '#28180d',
        'primary-fixed': '#ffdcbd',
        'on-secondary': '#3f2c20',
        'on-tertiary-fixed-variant': '#4c463e',
        background: '#131313',
        outline: '#9c8e82',
        'on-primary': '#482904',
        'on-background': '#e5e2e1',
        'on-surface-variant': '#d4c4b7',
        'surface-bright': '#393939',
        'surface-dim': '#131313',
        'surface-container-high': '#2a2a2a',
        'surface-container-lowest': '#0e0e0e',
        'on-tertiary-container': '#454038',
        surface: '#131313',
        'surface-tint': '#f0bd8b',
        'surface-variant': '#353535',
        'on-primary-container': '#5b3912',
        primary: '#f2be8c',
        'error-container': '#93000a',
        'surface-container': '#20201f',
        'on-secondary-container': '#ccb09f',
        'inverse-surface': '#e5e2e1',
        'primary-container': '#d4a373',
        'on-error': '#690005',
        'secondary-fixed': '#fbddca',
      },
      borderRadius: { DEFAULT: '0.125rem', lg: '0.25rem', xl: '0.5rem', full: '0.75rem' },
      spacing: {
        gutter: '2rem', 'unit-lg': '2rem', 'unit-xs': '0.25rem',
        'margin-mobile': '1.5rem', 'unit-md': '1rem', 'margin-desktop': '4rem',
        'container-max': '1280px', 'unit-xl': '4rem', 'unit-sm': '0.5rem',
      },
      fontFamily: {
        'headline-xl': ['Libre Caslon Text'],
        'body-md': ['Manrope'],
        'body-lg': ['Manrope'],
        'headline-lg': ['Libre Caslon Text'],
        'label-md': ['Geist'],
        'label-sm': ['Geist'],
        'headline-md': ['Libre Caslon Text'],
        'headline-lg-mobile': ['Libre Caslon Text'],
      },
      fontSize: {
        'headline-xl': ['60px', { lineHeight: '72px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-lg': ['40px', { lineHeight: '48px', fontWeight: '700' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.08em', fontWeight: '500' }],
        'headline-md': ['28px', { lineHeight: '36px', fontWeight: '600' }],
        'headline-lg-mobile': ['32px', { lineHeight: '40px', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
}
